### PR TITLE
Add http proxy and libvirt support

### PR DESCRIPTION
**Pull request by mulcahys**

### CODE REVIEW

**Comment by mulcahys** [comment]
This is still incomplete - gets as far as the kubeadm run before failing (I suspect because it can't pull the images)

```
    fedora: [controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
    fedora: [etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
    fedora: [init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
    fedora: [init] This often takes around a minute; or longer if the control plane images have to be pulled.
    fedora: Unfortunately, an error has occurred:
    fedora: 	
    fedora: timed out waiting for the condition
    fedora: This error is likely caused by that:
    fedora: 	
    fedora: - The kubelet is not running
    fedora: 	
    fedora: - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
    fedora: 	
    fedora: - There is no internet connection; so the kubelet can't pull the following control plane images:
    fedora: 	
    fedora: 	
    fedora: - 
    fedora: gcr.io/google_containers/kube-apiserver-amd64:v1.8.5
    fedora: 	
    fedora: 	
    fedora: - 
    fedora: gcr.io/google_containers/kube-controller-manager-amd64:v1.8.5
    fedora: 	
    fedora: 	
    fedora: - 
    fedora: gcr.io/google_containers/kube-scheduler-amd64:v1.8.5
    fedora: You can troubleshoot this for example with the following commands if you're on a systemd-powered system:
    fedora: 	
    fedora: - 'systemctl status kubelet'
    fedora: 	
    fedora: - 'journalctl -xeu kubelet'
```

kubelet log output supports that
```

Feb 22 10:45:04 kubespawndefault0 kubelet[339]: E0222 10:45:04.535404     339 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: remote error: tls: access denied
Feb 22 10:45:04 kubespawndefault0 kubelet[339]: E0222 10:45:04.535519     339 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "kube-scheduler-kubespawndefault0_kube-system(71ce261fcd0991c9619e2ae23033f88c)" failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: remote error: tls: access denied
Feb 22 10:45:04 kubespawndefault0 kubelet[339]: E0222 10:45:04.535588     339 kuberuntime_manager.go:633] createPodSandbox for pod "kube-scheduler-kubespawndefault0_kube-system(71ce261fcd0991c9619e2ae23033f88c)" failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: remote error: tls: access denied

```

**Comment by mulcahys** [comment]
Need to propagate the proxy settings into systemd-nspawn containers, or teach kubeadm about proxies (I thought it picked up proxy settings from the environment but doesn't seem to be happening here)

**Comment by mulcahys** [comment]
Successfully standing up behind a http proxy with the latest patch

```
    fedora: [addons] Applied essential addon: kube-dns
    fedora: [addons] Applied essential addon: kube-proxy
    fedora: 
    fedora: Your Kubernetes master has initialized successfully!
    fedora: 
    fedora: To start using your cluster, you need to run (as a regular user):
    fedora: 
    fedora:   mkdir -p $HOME/.kube
    fedora:   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    fedora:   sudo chown $(id -u):$(id -g) $HOME/.kube/config
    fedora: 
    fedora: You should now deploy a pod network to the cluster.
    fedora: Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
    fedora:   http://kubernetes.io/docs/admin/addons/
    fedora: 
    fedora: You can now join any number of machines by running the following on each node
    fedora: as root:
    fedora: 
    fedora:   kubeadm join --token 6d7c5f.eb26a6f2d2f0bf91 10.22.0.2:6443 --discovery-token-ca-cert-hash sha256:ad5d982f0cf7f7edf1ddad69fc4322b2cc21fc0e6a97c5ae8dc0a5071e7485ed
    fedora: Connection to machine kubespawndefault0 terminated.
    fedora: Connected to machine kubespawndefault0. Press ^] three times within 1s to exit session.
    fedora: Unable to connect to the server: remote error: tls: access denied
    fedora: Connection to machine kubespawndefault0 terminated.
    fedora: Connected to machine kubespawndefault1. Press ^] three times within 1s to exit session.
    fedora: [kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
    fedora: [preflight] Skipping pre-flight checks
    fedora: [discovery] Trying to connect to API Server "10.22.0.2:6443"
    fedora: [discovery] Created cluster-info discovery client, requesting info from "https://10.22.0.2:6443"
    fedora: [discovery] Cluster info signature and contents are valid and no TLS pinning was specified, will use API Server "10.22.0.2:6443"
    fedora: [discovery] Successfully established connection with API Server "10.22.0.2:6443"
    fedora: [bootstrap] Detected server version: v1.8.5
    fedora: [bootstrap] The server supports the Certificates API (certificates.k8s.io/v1beta1)
    fedora: 
    fedora: Node join complete:
    fedora: * Certificate signing request sent to master and response
    fedora:   received.
    fedora: * Kubelet informed of new secure connection details.
    fedora: 
    fedora: Run 'kubectl get nodes' on the master to see this machine join.
    fedora: Connection to machine kubespawndefault1 terminated.
    fedora: cluster "default" initialized
    fedora: Note: For kubectl to work, please set $KUBECONFIG:
    fedora: export KUBECONFIG=/var/lib/kube-spawn/default/kubeconfig
    fedora: + '[' true == true ']'
    fedora: ++ grep server /var/lib/kube-spawn/default/kubeconfig
    fedora: ++ awk '{print $2;}'
    fedora: ++ perl -pe 's/(https|http):\/\///g'
    fedora: + APISERVER_IP_PORT=10.22.0.2:6443
    fedora: ++ echo 10.22.0.2:6443
    fedora: ++ perl -pe 's/:\d*$//g'
    fedora: + APISERVER_IP=10.22.0.2
    fedora: ++ echo 10.22.0.2:6443
    fedora: ++ perl -pe 's/^[\d.]+://g'
    fedora: + APISERVER_PORT=6443
    fedora: + echo '0.0.0.0 6443 10.22.0.2 6443'
    fedora: + sudo tee /etc/rinetd.conf
    fedora: + sudo systemctl enable rinetd
    fedora: Created symlink /etc/systemd/system/multi-user.target.wants/rinetd.service → /usr/lib/systemd/system/rinetd.service.
    fedora: + sudo systemctl start rinetd
    fedora: + cd /home/vagrant
    fedora: ++ ip addr show eth0
    fedora: ++ awk '{print $2}'
    fedora: ++ grep 'inet\b'
    fedora: ++ cut -d/ -f1
    fedora: + VAGRANT_IP=192.168.121.212
    fedora: + cp /var/lib/kube-spawn/default/kubeconfig .
    fedora: + perl -pi.back -e 's/10.22.0.2/192.168.121.212/g;' kubeconfig
    fedora: + perl -pi.back -e 's/certificate-authority-data.*/insecure-skip-tls-verify: true/g;' kubeconfig

```

**Comment by dongsupark** [comment]
Thanks for the PR.
There are merge conflicts at the moment. Can you please rebase on the current master?

**Comment by mulcahys** [comment]
@dongsupark rebased, apologies for the delay but only getting a chance to look at this now. FWIW, my Go hacks are ugly enough but local testing shows it working - no objection to someone reworking it to look better though.

**Comment by mulcahys** [comment]
@dongsupark ah, missed the refactoring in 924bb3b41a4126a4c89e4be8779ac014f0d41151 - will need to do more a more extensive rebase

**Pull request closed without merging**
