### PR TITLE
readme: add instruction to get kubectl

### PR DESCRIPTION
**Pull request by alban**
Fixes https://github.com/kinvolk/kube-spawn/issues/175

### CODE REVIEW

**Comment by zeenix** [comment]
But with kube-spawn you already have the binary, just need to add the binary to the path so this would be redundant.

**Comment by krnowak** [comment]
Is it important to have a version of kubectl that matches a version of kubernetes kube-spawn is using?

Maybe it would be better to tell the user where kube-spawn puts kubectl and other tools, so the user can decide what to do with it.

**Comment by alban** [comment]
> Is it important to have a version of kubectl that matches a version of kubernetes kube-spawn is using?

It does not seem to be too important: I have kubectl 1.8.3 installed on my laptop and it works with Kubernetes 1.7. Maybe the other way around could cause problems? I don't know.

> Maybe it would be better to tell the user where kube-spawn puts kubectl and other tools, so the user can decide what to do with it.

Do you mean to tell the user via the README.md or via a `fmt.Printf` after a `kube-spawn start`?

**Comment by robertgzr** [comment]
What about `kube-spawn` checking the installed version and if there is a mismatch/ or no `kubectl` installed, notifying the user?

**Comment by krnowak** [comment]
Unless you put the message in a nice box and some terminalesque `<blink>` tag. ;)

**Comment by dongsupark** [comment]
@robertgzr Actually I already made a PR to check the versions: https://github.com/kinvolk/kube-spawn/pull/164
Then afterwards I just throw it away, as we introduced restructuring of configs. Right now we don't need to check it any more, as different versions are stored in different directories.

So I agree with adding just a simple description in README. I don't care about the details, but the description should be there. Even if there's no problem with version mismatches, there might be problems in the future.

**Pull request merged**
