### PR TITLE
Add gofmt check

### PR DESCRIPTION
**Pull request by donbowman**
This PR fixes a few lint/fmt errors.
It then adds lint & fmt to the pipeline to prevent checking in code w/ fmt errors.

### CODE REVIEW

**Comment by donbowman** [comment]
consider also running golangci-lint run $(go list ./... |sed -e 's?^_??' | grep -v /vendor/)

**Comment by dongsupark** [comment]
I think, this PR fixes real bugs as well as missing error checks. So I'm totally fine with code itself. Thanks!

About updating travis config, I'm not 100% sure.

First of all, I'm fine with adding `gofmt` checks in the travis config.

On the other hand, as for adding `golint` checks in the travis config, I'm not sure if that's a good idea. Clearly running `golint` for a code base mostly helps us fix issues. Mostly it reports valid coding style fixes. But sometimes golint is too strict. For example `Api` vs `API`. So from my understanding, it's not always possible to fix every case reported by golint.

**Comment by donbowman** [comment]
this is why i used errcheck mode of golint. its not style check.

**Comment by dongsupark** [comment]
Aha, `golangci-lint` allows for running only a specific linter `errcheck`. That makes sense.
Then it looks good to me.

**Pull request merged**
