### PR TITLE
Update glide

### PR DESCRIPTION
**Pull request by robertgzr**
Needs #53  #57

### CODE REVIEW

**Comment by robertgzr** [comment]
You can compare here: 
https://github.com/kinvolk/kube-spawn/compare/dongsu/vagrant-init-fixes...robertgzr/update-glide#diff-395f41b2a27b70ce44399c91c82158c2

I have moved all our direct dependencies to glide.yaml

**Comment by robertgzr** [comment]
And that's why I put needs #53 in the description... I will rebase this once #53 is merged and also include the semver package

**Comment by dongsupark** [comment]
@robertgzr Aha, I see. 
But it needs rebase after merging #53. Sorry!

**Comment by robertgzr** [comment]
@dongsupark rebased

**Comment by dongsupark** [comment]
@robertgzr LGTM

**Pull request merged**
