### PR TITLE
Add support for CNI plugin canal

### PR DESCRIPTION
**Pull request by donbowman**
Similar to flannel + calico, this will allow using canal.

### CODE REVIEW

**Comment by donbowman** [comment]
any word on this one?

**Comment by dongsupark** [comment]
I'll try to review it in this week.
It's just that other bug fixes have higher priorities.

**Comment by dongsupark** [comment]
I've just tested this PR, and it looks good.
It works with both k8s v1.10 and v1.11.
Code is also simple enough to understand.

But why do we need the second commit?
"Merge remote-tracking branch 'upstream/master' into add-canal-cni"

**Comment by donbowman** [comment]
the 2nd is just the merge from master so that this would apply clean, it should have no local changes

**Pull request merged**
